name: Deploy to Hosted Service

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Deploy to Hosted Servce
        run: |
          npm i -g yarn
          yarn --frozen-lockfile
          yarn codegen
          yarn build
          npx graph deploy --product hosted-service --access-token ${{secrets.GRAPH_ACCESS_TOKEN}} aavegotchi/aavegotchi-svg
        shell: bash
