name: Deploy Graph

on:
  push:
    branches: feat/ghActionDeployment
  pull_request:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v1
        with:
          node-version: 14
      - name: Install
        run: yarn --frozen-lockfile
      - name: Codegen
        run: yarn codegen
      - name: Build
        run: yarn build
      - uses: gtaschuk/graph-deploy@v0.1.0
        with:
          graph_access_token: ${{secrets.GRAPH_ACCESS_TOKEN}}
          graph_subgraph_name: "aavegotchi-svg"
          graph_account: "froid1911"
          graph_config_file: "subgraph.yml"
